# Generated by Django 4.0.2 on 2022-03-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
