# Generated by Django 4.0.2 on 2022-03-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_user_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_fname', models.CharField(max_length=50)),
                ('doc_lname', models.CharField(max_length=50)),
                ('doc_dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('hospital', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
