# Generated by Django 4.0.2 on 2022-03-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='userpic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to='')),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
