# Generated by Django 4.0.2 on 2022-03-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_userpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorpic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_fname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to='')),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
