# Generated by Django 4.0.2 on 2022-03-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_doctorpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='type',
            field=models.CharField(default='doc', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='user', max_length=10),
            preserve_default=False,
        ),
    ]
