# Generated by Django 4.0.2 on 2022-03-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0006_doctor_type_user_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='patient',
        ),
    ]
