# Generated by Django 4.0.2 on 2022-03-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_rename_user_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpic',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='userimages'),
        ),
    ]
