# Generated by Django 4.0.2 on 2022-03-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0009_alter_userpic_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpic',
            name='doctor_fname',
        ),
        migrations.RemoveField(
            model_name='userpic',
            name='user_fname',
        ),
    ]
