# Generated by Django 4.0.2 on 2022-03-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0010_remove_doctorpic_doctor_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pname', models.CharField(max_length=100)),
                ('testname', models.CharField(max_length=100)),
                ('refby', models.CharField(max_length=100)),
                ('date_of_report', models.DateField()),
                ('summary', models.CharField(max_length=100)),
                ('report', models.FileField(upload_to='')),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
