# Generated by Django 4.0.2 on 2022-03-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0011_patientreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='summary',
            field=models.TextField(max_length=100),
        ),
    ]
