# Generated by Django 4.0.2 on 2022-03-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0012_alter_patientreport_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='report',
            field=models.FileField(upload_to='flow/reports'),
        ),
    ]
