# Generated by Django 4.0.2 on 2022-03-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0013_alter_patientreport_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('sys', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('temp', models.FloatField()),
                ('spo2', models.IntegerField()),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctorpic',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='flow/images'),
        ),
    ]
