# Generated by Django 4.0.2 on 2022-03-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0014_vital_alter_doctorpic_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='patdoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_email', models.CharField(max_length=50)),
                ('patient_email', models.CharField(max_length=50)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
