# Generated by Django 4.0.2 on 2022-03-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0015_patdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='feedback',
            field=models.TextField(default='', max_length=500),
        ),
    ]
