# Generated by Django 4.0.2 on 2022-03-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0016_patientreport_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreport',
            name='id',
        ),
        migrations.AddField(
            model_name='patientreport',
            name='report_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
