# Generated by Django 4.0.2 on 2022-03-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0018_alter_patientreport_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='feedback',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
