# Generated by Django 4.0.2 on 2022-03-29 14:43

from django.db import migrations, models
import flow.models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0019_alter_patientreport_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sleep', models.IntegerField()),
                ('smoke', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('alcohol', models.IntegerField()),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patientreport',
            name='report_id',
            field=models.IntegerField(default=flow.models.incrementrepid, editable=False, primary_key=True, serialize=False),
        ),
    ]
