# Generated by Django 4.0.2 on 2022-04-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0021_vital_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
