# Generated by Django 4.0.2 on 2022-05-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0022_patient_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='querylog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
