# Generated by Django 4.0.2 on 2022-05-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0023_querylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='querylog',
        ),
    ]
