# Generated by Django 4.0.2 on 2022-05-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0024_delete_querylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='querylog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('query_type', models.TextField(blank=True, default='', max_length=1000)),
                ('issue', models.TextField(blank=True, default='', max_length=1000)),
                ('problem_domain', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
